ALTER TABLE system ALTER COLUMN total_memory TYPE BIGINT;
ALTER TABLE system ALTER COLUMN used_memory TYPE BIGINT;
ALTER TABLE system ALTER COLUMN total_swap TYPE BIGINT;
ALTER TABLE system ALTER COLUMN used_swap TYPE BIGINT;